#include makefile for z/OS
PLATFORM=_ZOS
PORTDIR=zos
CC=c++
GCC=c++
LINK=c++
LINK_OPT= -Wl,dll,xplink
LD_OPT=
OBJOPT=-o"$@"
ARCHIVE=ar -r 
ARC_EXT=a
CFLAGS= -D__BIG_ENDIAN -c -O3 -Wc,ilp32,expo,dll,xplink -Wc,"LANG(EXTENDED),CONVLIT(ISO8859-1)"
LIB_EXT=so
EXE_EXT=
LIBFLAGS= 
LIB_OBJOPT=-o"$@"
LIBPATH=
EXEFLAGS=
EXELIBS=
JAVA_PLAT_INCLUDE=${JAVA_SDK_INCLUDE}
LIB_PREFIX=lib
COPY_CONNECTOR=

