#include makefile for z/OS
PLATFORM=_ZOS
PORTDIR=zos
CC=c++
GCC=c++
LINK=c++
LINK_OPT= -Wl,lp64,AMODE=64 -Wl,dll,xplink
LD_OPT=
OBJOPT=-o"$@"
ARCHIVE=ar -r 
ARC_EXT=a
CFLAGS= -D_64BIT -D__BIG_ENDIAN -c -g -Wc,lp64,warn64,expo,dll -Wc,"LANG(EXTENDED)"
LIB_EXT=so
EXE_EXT=
LIBFLAGS= 
LIB_OBJOPT=-o"$@"
LIBPATH=
EXEFLAGS=
EXELIBS=
JAVA_PLAT_INCLUDE=${JAVA_SDK_INCLUDE}
LIB_PREFIX=lib
COPY_CONNECTOR=

