/*******************************************************************************
 * Licensed Materials - Property of IBM
 * "Restricted Materials of IBM"
 *
 * (c) Copyright IBM Corp. 1998, 2014 All Rights Reserved
 *
 * US Government Users Restricted Rights - Use, duplication or disclosure
 * restricted by GSA ADP Schedule Contract with IBM Corp.
 *******************************************************************************/

/**
 * @file
 * @ingroup Port
 * @brief Port Library Error Codes
 *
 * When an error is reported by the operating system the port library must translate this OS specific error code to a 
 * portable error code.  All portable error codes are negative numbers.  Not every module of the port library will have
 * error codes dedicated to it's own use, some will use the generic portable error code values.
 *
 * Errors reported by the OS may be recorded by calling the port library functions @ref j9error.c::j9error_set_last_error "j9error_set_last_error()"
 * or @ref j9error.c::j9error_set_last_error_with_message "j9error_set_last_error_with_message()".  The mapping of the OS specific error
 * code to a portable error code is the responsibility of the calling module.
 */
#ifndef j9porterror_h
#define j9porterror_h


/**
 * @name Generic Errors
 * Generic error codes for modules that do not have their own specific errors.  Where possible it is recommended that all
 * modules that return error codes have their own set
 *
 * @internal J9PORT_ERROR* range from -1 to -99 avoid overlap
 * @{
 */
#define J9PORT_ERROR_BASE -1
#define J9PORT_ERROR_OPFAILED J9PORT_ERROR_BASE
#define J9PORT_ERROR_EOF (J9PORT_ERROR_BASE-1)
#define J9PORT_ERROR_NOPERMISSION (J9PORT_ERROR_BASE-2)
#define J9PORT_ERROR_NOTFOUND (J9PORT_ERROR_BASE-3)
#define J9PORT_ERROR_NAMETOOLONG (J9PORT_ERROR_BASE-4)
#define J9PORT_ERROR_DISKFULL (J9PORT_ERROR_BASE-5)
#define J9PORT_ERROR_EXIST (J9PORT_ERROR_BASE-6)
#define J9PORT_ERROR_NOTEXIST (J9PORT_ERROR_BASE-7)
#define J9PORT_ERROR_SYSTEMFULL (J9PORT_ERROR_BASE-8)
#define J9PORT_ERROR_NOENT (J9PORT_ERROR_BASE-9)
#define J9PORT_ERROR_DIRECTORY (J9PORT_ERROR_BASE-10)
#define J9PORT_ERROR_NOTDIRECTORY (J9PORT_ERROR_BASE-11)
#define J9PORT_ERROR_LOOP (J9PORT_ERROR_BASE-12)
#define J9PORT_ERROR_BADF (J9PORT_ERROR_BASE-13)
#define J9PORT_ERROR_WOULDBLOCK (J9PORT_ERROR_BASE-14)
#define J9PORT_ERROR_INVALID (J9PORT_ERROR_BASE-15)
#define J9PORT_ERROR_FILE_LOCK_VIOLATION (J9PORT_ERROR_BASE-16)
#define J9PORT_ERROR_INVALID_HANDLE (J9PORT_ERROR_BASE-17)
#define J9PORT_ERROR_NOT_SUPPORTED_ON_THIS_PLATFORM (J9PORT_ERROR_BASE-18)
#define J9PORT_ERROR_INVALID_ARGUMENTS (J9PORT_ERROR_BASE-19)
/** @} */

/** 
 * @name Port Library startup failure code
 * Failures related to the initialization and startup of the port library.
 *
 * @internal J9PORT_ERROR_STARTUP* range from -100 to -149 to avoid overlap
 * @{
 */
#define J9PORT_ERROR_STARTUP_BASE -100
#define J9PORT_ERROR_STARTUP_THREAD (J9PORT_ERROR_STARTUP_BASE)
#define J9PORT_ERROR_STARTUP_MEM (J9PORT_ERROR_STARTUP_BASE -1)
#define J9PORT_ERROR_STARTUP_TLS (J9PORT_ERROR_STARTUP_BASE -2)
#define J9PORT_ERROR_STARTUP_TLS_ALLOC (J9PORT_ERROR_STARTUP_BASE -3)
#define J9PORT_ERROR_STARTUP_TLS_MUTEX (J9PORT_ERROR_STARTUP_BASE -4)
#define J9PORT_ERROR_STARTUP_CPU (J9PORT_ERROR_STARTUP_BASE -5)
#define J9PORT_ERROR_STARTUP_VMEM (J9PORT_ERROR_STARTUP_BASE -6)
#define J9PORT_ERROR_STARTUP_FILE (J9PORT_ERROR_STARTUP_BASE -7)
#define J9PORT_ERROR_STARTUP_TTY (J9PORT_ERROR_STARTUP_BASE -8)
#define J9PORT_ERROR_STARTUP_TTY_HANDLE (J9PORT_ERROR_STARTUP_BASE -9)
#define J9PORT_ERROR_STARTUP_TTY_CONSOLE (J9PORT_ERROR_STARTUP_BASE -10)
#define J9PORT_ERROR_STARTUP_MMAP (J9PORT_ERROR_STARTUP_BASE -11)
#define J9PORT_ERROR_STARTUP_IPCMUTEX (J9PORT_ERROR_STARTUP_BASE -12)
#define J9PORT_ERROR_STARTUP_NLS (J9PORT_ERROR_STARTUP_BASE -13)
#define J9PORT_ERROR_STARTUP_SOCK (J9PORT_ERROR_STARTUP_BASE -14)
#define J9PORT_ERROR_STARTUP_TIME (J9PORT_ERROR_STARTUP_BASE -15)
#define J9PORT_ERROR_STARTUP_GP (J9PORT_ERROR_STARTUP_BASE -16)
#define J9PORT_ERROR_STARTUP_EXIT (J9PORT_ERROR_STARTUP_BASE -17)
#define J9PORT_ERROR_STARTUP_SYSINFO (J9PORT_ERROR_STARTUP_BASE -18)
#define J9PORT_ERROR_STARTUP_SL (J9PORT_ERROR_STARTUP_BASE -19)
#define J9PORT_ERROR_STARTUP_STR (J9PORT_ERROR_STARTUP_BASE -20)
#define J9PORT_ERROR_STARTUP_SHSEM (J9PORT_ERROR_STARTUP_BASE -21)
#define J9PORT_ERROR_STARTUP_SHMEM (J9PORT_ERROR_STARTUP_BASE -22)
#define J9PORT_ERROR_STARTUP_ERROR (J9PORT_ERROR_STARTUP_BASE -23)
#define J9PORT_ERROR_STARTUP_SIGNAL (J9PORT_ERROR_STARTUP_BASE -24)
#define J9PORT_ERROR_STARTUP_AIX_PROC_ATTR (J9PORT_ERROR_STARTUP_BASE -25)
#define J9PORT_ERROR_STARTUP_SHMEM_MOSERVICE (J9PORT_ERROR_STARTUP_BASE -26)
#define J9PORT_ERROR_STARTUP_DUMP (J9PORT_ERROR_STARTUP_BASE -27)

/** @} */

/**
 * @name Shared Semaphore Errors
 * Error codes for shared semaphore operations.
 *
 * @internal J9PORT_ERROR_SHSEM* range from at -150 to 169 to avoid overlap 
 * @{
 */
#define J9PORT_ERROR_SHSEM_BASE -150
#define J9PORT_ERROR_SHSEM_OPFAILED (J9PORT_ERROR_SHSEM_BASE)
#define J9PORT_ERROR_SHSEM_HANDLE_INVALID (J9PORT_ERROR_SHSEM_BASE-1)
#define J9PORT_ERROR_SHSEM_SEMSET_INVALID (J9PORT_ERROR_SHSEM_BASE-2)
#define J9PORT_ERROR_SHSEM_OPFAILED_DONT_UNLINK (J9PORT_ERROR_SHSEM_BASE-3)
#define J9PORT_ERROR_SHSEM_OPFAILED_CONTROL_FILE_CORRUPT (J9PORT_ERROR_SHSEM_BASE-4)
#define J9PORT_ERROR_SHSEM_OPFAILED_SEMID_MISMATCH (J9PORT_ERROR_SHSEM_BASE-5)
#define J9PORT_ERROR_SHSEM_OPFAILED_SEM_KEY_MISMATCH (J9PORT_ERROR_SHSEM_BASE-6)
#define J9PORT_ERROR_SHSEM_OPFAILED_SEM_SIZE_CHECK_FAILED (J9PORT_ERROR_SHSEM_BASE-7)
#define J9PORT_ERROR_SHSEM_OPFAILED_SEM_MARKER_CHECK_FAILED (J9PORT_ERROR_SHSEM_BASE-8)
#define J9PORT_ERROR_SHSEM_DATA_DIRECTORY_FAILED (J9PORT_ERROR_SHSEM_BASE-9)
#define J9PORT_ERROR_SHSEM_WAIT_FOR_CREATION_MUTEX_TIMEDOUT (J9PORT_ERROR_SHSEM_BASE-10)
#define J9PORT_ERROR_SHSEM_STAT_BUFFER_INVALID (J9PORT_ERROR_SHSEM_BASE-11)
#define J9PORT_ERROR_SHSEM_STAT_FAILED (J9PORT_ERROR_SHSEM_BASE-12)
#define J9PORT_ERROR_SHSEM_OPFAILED_SEMAPHORE_NOT_FOUND (J9PORT_ERROR_SHSEM_BASE-13)
#define J9PORT_ERROR_SHSEM_OPFAILED_CONTROL_FILE_LOCK_FAILED (J9PORT_ERROR_SHSEM_BASE-14)

/** @} */

/**
 * @name Shared Memory Errors
 * Error codes for shared memory semaphore operations.
 *
 * @internal J9PORT_ERROR_SHMEM* range from at -170 to -189 to avoid overlap 
 * @{
 */
#define J9PORT_ERROR_SHMEM_BASE -170
#define J9PORT_ERROR_SHMEM_OPFAILED (J9PORT_ERROR_SHMEM_BASE)
#define J9PORT_ERROR_SHMEM_OPEN_ATTACHED_FAILED (J9PORT_ERROR_SHMEM_BASE-1)
#define J9PORT_ERROR_SHMEM_CREATE_ATTACHED_FAILED (J9PORT_ERROR_SHMEM_BASE-2)
#define J9PORT_ERROR_SHMEM_NOSPACE (J9PORT_ERROR_SHMEM_BASE-3)
#define J9PORT_ERROR_SHMEM_TOOBIG (J9PORT_ERROR_SHMEM_BASE-4)
#define J9PORT_ERROR_SHMEM_DATA_DIRECTORY_FAILED (J9PORT_ERROR_SHMEM_BASE-5)
#define J9PORT_ERROR_SHMEM_WAIT_FOR_CREATION_MUTEX_TIMEDOUT (J9PORT_ERROR_SHMEM_BASE-6)
#define J9PORT_ERROR_SHMEM_ZOS_STORAGE_KEY_READONLY (J9PORT_ERROR_SHMEM_BASE-7)
#define J9PORT_ERROR_SHMEM_OPFAILED_CONTROL_FILE_CORRUPT (J9PORT_ERROR_SHMEM_BASE-8)
#define J9PORT_ERROR_SHMEM_OPFAILED_SHMID_MISMATCH (J9PORT_ERROR_SHMEM_BASE-9)
#define J9PORT_ERROR_SHMEM_OPFAILED_SHM_KEY_MISMATCH (J9PORT_ERROR_SHMEM_BASE-10)
#define J9PORT_ERROR_SHMEM_OPFAILED_SHM_GROUPID_CHECK_FAILED (J9PORT_ERROR_SHMEM_BASE-11)
#define J9PORT_ERROR_SHMEM_OPFAILED_SHM_USERID_CHECK_FAILED (J9PORT_ERROR_SHMEM_BASE-12)
#define J9PORT_ERROR_SHMEM_OPFAILED_SHM_SIZE_CHECK_FAILED (J9PORT_ERROR_SHMEM_BASE-13)
#define J9PORT_ERROR_SHMEM_HANDLE_INVALID (J9PORT_ERROR_SHMEM_BASE-14)
#define J9PORT_ERROR_SHMEM_STAT_BUFFER_INVALID (J9PORT_ERROR_SHMEM_BASE-15)
#define J9PORT_ERROR_SHMEM_STAT_FAILED (J9PORT_ERROR_SHMEM_BASE-16)
#define J9PORT_ERROR_SHMEM_OPFAILED_SHARED_MEMORY_NOT_FOUND (J9PORT_ERROR_SHMEM_BASE-17)
#define J9PORT_ERROR_SHMEM_OPFAILED_CONTROL_FILE_LOCK_FAILED (J9PORT_ERROR_SHMEM_BASE-18)

/** @} */

/* -190 to -199 available for use */

/**
 * @name Socket Errors
 * Error codes for socket operations
 *
 * @internal J9PORT_ERROR_SOCKET* range from -200 to -299 avoid overlap
 * @{
 */
#define J9PORT_ERROR_SOCKET_BASE -200
#define J9PORT_ERROR_SOCKET_BADSOCKET J9PORT_ERROR_SOCKET_BASE						/* generic error */
#define J9PORT_ERROR_SOCKET_NOTINITIALIZED (J9PORT_ERROR_SOCKET_BASE-1)				/* socket library uninitialized */
#define J9PORT_ERROR_SOCKET_BADAF (J9PORT_ERROR_SOCKET_BASE-2)						/* bad address family */
#define J9PORT_ERROR_SOCKET_BADPROTO (J9PORT_ERROR_SOCKET_BASE-3)					/* bad protocol */
#define J9PORT_ERROR_SOCKET_BADTYPE (J9PORT_ERROR_SOCKET_BASE-4)					/* bad type */
#define J9PORT_ERROR_SOCKET_SYSTEMBUSY (J9PORT_ERROR_SOCKET_BASE-5)					/* system busy handling requests */
#define J9PORT_ERROR_SOCKET_SYSTEMFULL (J9PORT_ERROR_SOCKET_BASE-6)					/* too many sockets */
#define J9PORT_ERROR_SOCKET_NOTCONNECTED (J9PORT_ERROR_SOCKET_BASE-7)				/* socket is not connected */
#define J9PORT_ERROR_SOCKET_INTERRUPTED	(J9PORT_ERROR_SOCKET_BASE-8)				/* the call was cancelled */
#define J9PORT_ERROR_SOCKET_TIMEOUT	(J9PORT_ERROR_SOCKET_BASE-9)					/* the operation timed out */
#define J9PORT_ERROR_SOCKET_CONNRESET (J9PORT_ERROR_SOCKET_BASE-10)					/* the connection was reset */
#define J9PORT_ERROR_SOCKET_WOULDBLOCK	( J9PORT_ERROR_SOCKET_BASE-11)				/* the socket is marked as nonblocking operation would block */
#define J9PORT_ERROR_SOCKET_ADDRNOTAVAIL (J9PORT_ERROR_SOCKET_BASE-12)				/* address not available */
#define J9PORT_ERROR_SOCKET_ADDRINUSE (J9PORT_ERROR_SOCKET_BASE-13)					/* address already in use */
#define J9PORT_ERROR_SOCKET_NOTBOUND (J9PORT_ERROR_SOCKET_BASE-14)					/* the socket is not bound */
#define J9PORT_ERROR_SOCKET_UNKNOWNSOCKET (J9PORT_ERROR_SOCKET_BASE-15)				/* resolution of fileDescriptor to socket failed */
#define J9PORT_ERROR_SOCKET_INVALIDTIMEOUT (J9PORT_ERROR_SOCKET_BASE-16)			/* the specified timeout is invalid */
#define J9PORT_ERROR_SOCKET_FDSETFULL (J9PORT_ERROR_SOCKET_BASE-17)					/* Unable to create an FDSET */
#define J9PORT_ERROR_SOCKET_TIMEVALFULL (J9PORT_ERROR_SOCKET_BASE-18)				/* Unable to create a TIMEVAL */
#define J9PORT_ERROR_SOCKET_REMSOCKSHUTDOWN (J9PORT_ERROR_SOCKET_BASE-19)			/* The remote socket has shutdown gracefully */
#define J9PORT_ERROR_SOCKET_NOTLISTENING (J9PORT_ERROR_SOCKET_BASE-20)				/* listen() was not invoked prior to accept() */
#define J9PORT_ERROR_SOCKET_NOTSTREAMSOCK (J9PORT_ERROR_SOCKET_BASE-21)				/* The socket does not support connection-oriented service */
#define J9PORT_ERROR_SOCKET_ALREADYBOUND (J9PORT_ERROR_SOCKET_BASE-22)				/* The socket is already bound to an address */
#define J9PORT_ERROR_SOCKET_NBWITHLINGER (J9PORT_ERROR_SOCKET_BASE-23)				/* The socket is marked non-blocking & SO_LINGER is non-zero */
#define J9PORT_ERROR_SOCKET_ISCONNECTED (J9PORT_ERROR_SOCKET_BASE-24)				/* The socket is already connected */
#define J9PORT_ERROR_SOCKET_NOBUFFERS (J9PORT_ERROR_SOCKET_BASE-25)					/* No buffer space is available */
#define J9PORT_ERROR_SOCKET_HOSTNOTFOUND (J9PORT_ERROR_SOCKET_BASE-26)				/* Authoritative Answer Host not found */
#define J9PORT_ERROR_SOCKET_NODATA (J9PORT_ERROR_SOCKET_BASE-27)					/* Valid name, no data record of requested type */
#define J9PORT_ERROR_SOCKET_BOUNDORCONN (J9PORT_ERROR_SOCKET_BASE-28)				/* The socket has not been bound or is already connected */
#define J9PORT_ERROR_SOCKET_OPNOTSUPP (J9PORT_ERROR_SOCKET_BASE-29)					/* The socket does not support the operation */
#define J9PORT_ERROR_SOCKET_OPTUNSUPP (J9PORT_ERROR_SOCKET_BASE-30)					/* The socket option is not supported */
#define J9PORT_ERROR_SOCKET_OPTARGSINVALID (J9PORT_ERROR_SOCKET_BASE-31)			/* The socket option arguments are invalid */
#define J9PORT_ERROR_SOCKET_SOCKLEVELINVALID (J9PORT_ERROR_SOCKET_BASE-32)			/* The socket level is invalid */
#define J9PORT_ERROR_SOCKET_TIMEOUTFAILURE (J9PORT_ERROR_SOCKET_BASE-33)			
#define J9PORT_ERROR_SOCKET_SOCKADDRALLOCFAIL (J9PORT_ERROR_SOCKET_BASE-34)			/* Unable to allocate the sockaddr structure */
#define J9PORT_ERROR_SOCKET_FDSET_SIZEBAD (J9PORT_ERROR_SOCKET_BASE-35)				/* The calculated maximum size of the file descriptor set is bad */
#define J9PORT_ERROR_SOCKET_UNKNOWNFLAG (J9PORT_ERROR_SOCKET_BASE-36)				/* The flag is unknown */
#define J9PORT_ERROR_SOCKET_MSGSIZE (J9PORT_ERROR_SOCKET_BASE-37)					/* The datagram was too big to fit the specified buffer & was truncated. */
#define J9PORT_ERROR_SOCKET_NORECOVERY (J9PORT_ERROR_SOCKET_BASE-38)				/* The operation failed with no recovery possible */
#define J9PORT_ERROR_SOCKET_ARGSINVALID (J9PORT_ERROR_SOCKET_BASE-39)				/* The arguments are invalid */
#define J9PORT_ERROR_SOCKET_BADDESC (J9PORT_ERROR_SOCKET_BASE-40)					/* The socket argument is not a valid file descriptor */
#define J9PORT_ERROR_SOCKET_NOTSOCK (J9PORT_ERROR_SOCKET_BASE-41)					/* The socket argument is not a socket */
#define J9PORT_ERROR_SOCKET_HOSTENTALLOCFAIL (J9PORT_ERROR_SOCKET_BASE-42)			/* Unable to allocate the hostent structure */
#define J9PORT_ERROR_SOCKET_TIMEVALALLOCFAIL (J9PORT_ERROR_SOCKET_BASE-43)			/* Unable to allocate the timeval structure */
#define J9PORT_ERROR_SOCKET_LINGERALLOCFAIL (J9PORT_ERROR_SOCKET_BASE-44)			/* Unable to allocate the linger structure */
#define J9PORT_ERROR_SOCKET_IPMREQALLOCFAIL (J9PORT_ERROR_SOCKET_BASE-45)			/* Unable to allocate the ipmreq structure */
#define J9PORT_ERROR_SOCKET_FDSETALLOCFAIL (J9PORT_ERROR_SOCKET_BASE-46)			/* Unable to allocate the fdset structure */
#define J9PORT_ERROR_SOCKET_OPFAILED (J9PORT_ERROR_SOCKET_BASE-47)
#define J9PORT_ERROR_SOCKET_VALUE_NULL (J9PORT_ERROR_SOCKET_BASE-48) 				/* The value indexed was NULL */
#define J9PORT_ERROR_SOCKET_CONNECTION_REFUSED	( J9PORT_ERROR_SOCKET_BASE-49)		/* connection was refused */
#define J9PORT_ERROR_SOCKET_ENETUNREACH (J9PORT_ERROR_SOCKET_BASE-50)				/* network is not reachable */
#define J9PORT_ERROR_SOCKET_EACCES (J9PORT_ERROR_SOCKET_BASE-51)					/* permissions do not allow action on socket */
#define J9PORT_ERROR_SOCKET_WAS_CLOSED (J9PORT_ERROR_SOCKET_BASE-52)				/* the socket was closed (set to NULL or INVALID) */
#define J9PORT_ERROR_SOCKET_EINPROGRESS (J9PORT_ERROR_SOCKET_BASE-53)				/* Non-blocking socket could not connect immediately, connect is happening asynchronously */
#define J9PORT_ERROR_SOCKET_ALREADYINPROGRESS (J9PORT_ERROR_SOCKET_BASE-54)			/* A connection attempt is already in progress on the socket */

/* Palm OS6 uses a hybrid error reporting mechanism.  Need to be able to distinguish socket
 * errors from all other errors (yuck this is really awful).
 */
#define J9PORT_ERROR_SOCKET_FIRST_ERROR_NUMBER J9PORT_ERROR_SOCKET_BASE
#define J9PORT_ERROR_SOCKET_LAST_ERROR_NUMBER J9PORT_ERROR_SOCKET_VALUE_NULL /* Equals last used error code */

/**
 * File operations system function call errno mappings
 * @internal
 * Errno for following system call functions:
 *  fstat
 * 	fstatfs (on Linux)
 * 	fstatvfs (on AIX)
 *
 * The errors are meant to be a 32 bit integer.
 * The most significant 16 bits will identify the failing function
 * The least significant 16 bits will identify the errno that occured while calling the function
 *
 */
#define J9PORT_ERROR_FILE_FSTAT_ERROR (-2<<16)
#define J9PORT_ERROR_FILE_FSTATFS_ERROR (-3<<16)
#define J9PORT_ERROR_FILE_FSTATVFS_ERROR (-3<<16)

/**
 * @name File Errors 
 * Error codes for file operations.
 *
 * @internal J9PORT_ERROR_FILE* range from -300 to -349 avoid overlap
 * @{
 */
#define J9PORT_ERROR_FILE_BASE -300
#define J9PORT_ERROR_FILE_OPFAILED (J9PORT_ERROR_FILE_BASE)
#define J9PORT_ERROR_FILE_EOF (J9PORT_ERROR_FILE_BASE-1)
#define J9PORT_ERROR_FILE_NOPERMISSION (J9PORT_ERROR_FILE_BASE-2)
#define J9PORT_ERROR_FILE_NOTFOUND (J9PORT_ERROR_FILE_BASE-3)
#define J9PORT_ERROR_FILE_NAMETOOLONG (J9PORT_ERROR_FILE_BASE-4)
#define J9PORT_ERROR_FILE_DISKFULL (J9PORT_ERROR_FILE_BASE-5)
#define J9PORT_ERROR_FILE_EXIST (J9PORT_ERROR_FILE_BASE-6)
#define J9PORT_ERROR_FILE_SYSTEMFULL (J9PORT_ERROR_FILE_BASE-7)
#define J9PORT_ERROR_FILE_NOENT (J9PORT_ERROR_FILE_BASE-8)
#define J9PORT_ERROR_FILE_NOTDIR (J9PORT_ERROR_FILE_BASE-9)
#define J9PORT_ERROR_FILE_LOOP (J9PORT_ERROR_FILE_BASE-10)
#define J9PORT_ERROR_FILE_BADF (J9PORT_ERROR_FILE_BASE-11)
#define J9PORT_ERROR_FILE_WOULDBLOCK (J9PORT_ERROR_FILE_BASE-12)
#define J9PORT_ERROR_FILE_INVAL (J9PORT_ERROR_FILE_BASE-13)
#define J9PORT_ERROR_FILE_LOCK_NOREADWRITE (J9PORT_ERROR_FILE_BASE-14)
#define J9PORT_ERROR_FILE_LOCK_NOWAITNOWAIT (J9PORT_ERROR_FILE_BASE-15)
#define J9PORT_ERROR_FILE_LOCK_BADLOCK (J9PORT_ERROR_FILE_BASE-16)
#define J9PORT_ERROR_FILE_UNLOCK_BADUNLOCK (J9PORT_ERROR_FILE_BASE-17)
#define J9PORT_ERROR_FILE_INTERRUPTED (J9PORT_ERROR_FILE_BASE-18)
#define J9PORT_ERROR_FILE_ISDIR (J9PORT_ERROR_FILE_BASE-19)
#define J9PORT_ERROR_FILE_PROCESS_MAX_OPEN (J9PORT_ERROR_FILE_BASE-20)
#define J9PORT_ERROR_FILE_XIO (J9PORT_ERROR_FILE_BASE-21)
#define J9PORT_ERROR_FILE_ROFS (J9PORT_ERROR_FILE_BASE-22)
#define J9PORT_ERROR_FILE_LOCK_EDEADLK (J9PORT_ERROR_FILE_BASE-23)
#define J9PORT_ERROR_FILE_EAGAIN (J9PORT_ERROR_FILE_BASE-24)
#define J9PORT_ERROR_FILE_EFAULT (J9PORT_ERROR_FILE_BASE-25)
#define J9PORT_ERROR_FILE_EINTR (J9PORT_ERROR_FILE_BASE-26)
#define J9PORT_ERROR_FILE_IO (J9PORT_ERROR_FILE_BASE-27)
#define J9PORT_ERROR_FILE_OVERFLOW (J9PORT_ERROR_FILE_BASE-28)
#define J9PORT_ERROR_FILE_SPIPE (J9PORT_ERROR_FILE_BASE-29)
#define J9PORT_ERROR_FILE_FSTAT_FAILED (J9PORT_ERROR_FILE_BASE-30)
#define J9PORT_ERROR_FILE_OPERATION_ABORTED (J9PORT_ERROR_FILE_BASE-31)
#define J9PORT_ERROR_FILE_NOT_ENOUGH_QUOTA (J9PORT_ERROR_FILE_BASE-32)
#define J9PORT_ERROR_FILE_INSUFFICIENT_BUFFER (J9PORT_ERROR_FILE_BASE-33)
#define J9PORT_ERROR_FILE_HANDLE_EOF (J9PORT_ERROR_FILE_BASE-34)
#define J9PORT_ERROR_FILE_BROKEN_PIPE (J9PORT_ERROR_FILE_BASE-35)
#define J9PORT_ERROR_FILE_MORE_DATA (J9PORT_ERROR_FILE_BASE-36)
#define J9PORT_ERROR_FILE_INVALID_PARAMETER (J9PORT_ERROR_FILE_BASE-37)
#define J9PORT_ERROR_FILE_IO_PENDING (J9PORT_ERROR_FILE_BASE-38)
#define J9PORT_ERROR_FILE_READ_NO_BYTES_READ (J9PORT_ERROR_FILE_BASE-39)

/** @} */

/**
 * @name Memory Mapping Errors 
 * Error codes for file operations.
 *
 * @internal J9PORT_ERROR_MMAP* range from -350 to -399 avoid overlap
 * @{
 */
#define J9PORT_ERROR_MMAP_BASE -350
#define J9PORT_ERROR_MMAP_MAP_FILE_INVALIDFILE (J9PORT_ERROR_MMAP_BASE)
#define J9PORT_ERROR_MMAP_MAP_FILE_UNSUPPORTEDWRITE (J9PORT_ERROR_MMAP_BASE-1)
#define J9PORT_ERROR_MMAP_MAP_FILE_INVALIDFLAGS (J9PORT_ERROR_MMAP_BASE-2)
#define J9PORT_ERROR_MMAP_MAP_FILE_MALLOCFAILED (J9PORT_ERROR_MMAP_BASE-3)
#define J9PORT_ERROR_MMAP_MAP_FILE_CREATEMAPPINGOBJECTFAILED (J9PORT_ERROR_MMAP_BASE-4)
#define J9PORT_ERROR_MMAP_MAP_FILE_MAPPINGFAILED (J9PORT_ERROR_MMAP_BASE-5)
#define J9PORT_ERROR_MMAP_MSYNC_INVALIDFLAGS (J9PORT_ERROR_MMAP_BASE-6)
#define J9PORT_ERROR_MMAP_MSYNC_FAILED (J9PORT_ERROR_MMAP_BASE-7)
#define J9PORT_ERROR_MMAP_MAP_FILE_STATFAILED (J9PORT_ERROR_MMAP_BASE-8)
/** @} */

/**
 * @name memory protection errors
 * Error codes for file operations.
 *
 * @internal J9PORT_ERROR_MMAP* range from -400 to -449 avoid overlap
 * @{
 */
#define J9PORT_PAGE_PROTECT_BASE -400
#define J9PORT_PAGE_PROTECT_FAILED (J9PORT_PAGE_PROTECT_BASE)
/** @} */

/**
 * @name vmem Errors 
 * Error codes for virtual memory operations.
 *
 * @internal J9PORT_ERROR_VMEM* range from -450 to -499 avoid overlap
 * @{
 */
#define J9PORT_ERROR_VMEM_BASE -450
#define J9PORT_ERROR_VMEM_OPFAILED (J9PORT_ERROR_VMEM_BASE)
#define J9PORT_ERROR_VMEM_INSUFFICENT_RESOURCES (J9PORT_ERROR_VMEM_BASE -1)
#define J9PORT_ERROR_VMEM_INVALID_PARAMS (J9PORT_ERROR_VMEM_BASE -2)

/** @} */

/**
 * @name signal Errors 
 * Error codes for signal memory operations.
 *
 * @internal J9PORT_ERROR_SIG* range from -500 to -549 avoid overlap
 * @{
 */
#define J9PORT_ERROR_SIG_BASE -500
#define J9PORT_ERROR_SIG_OPFAILED (J9PORT_ERROR_VMEM_BASE)
/** @} */

/**
 * @name process Errors 
 * Error codes for process operations.
 *
 * @internal J9PORT_ERROR_PROCESS* range from -550 to -599 avoid overlap
 * @{
 */
#define J9PORT_ERROR_PROCESS_BASE -550
#define J9PORT_ERROR_PROCESS_OPFAILED (J9PORT_ERROR_PROCESS_BASE)
#define J9PORT_ERROR_PROCESS_CLOSE_PROCHANDLE (J9PORT_ERROR_PROCESS_BASE-1)
#define J9PORT_ERROR_PROCESS_CLOSE_INHANDLE (J9PORT_ERROR_PROCESS_BASE-2)
#define J9PORT_ERROR_PROCESS_CLOSE_OUTHANDLE (J9PORT_ERROR_PROCESS_BASE-3)
#define J9PORT_ERROR_PROCESS_CLOSE_ERRHANDLE (J9PORT_ERROR_PROCESS_BASE-4)
#define J9PORT_ERROR_PROCESS_FREEMEMORY (J9PORT_ERROR_PROCESS_BASE-5)
#define J9PORT_ERROR_PROCESS_INVALID_STREAMFLAG (J9PORT_ERROR_PROCESS_BASE-6)
#define J9PORT_ERROR_PROCESS_INVALID_STREAMHANDLE (J9PORT_ERROR_PROCESS_BASE-7)
#define J9PORT_ERROR_PROCESS_INVALID_PARAMS (J9PORT_ERROR_PROCESS_BASE-8)
#define J9PORT_ERROR_PROCESS_NOPERMISSION (J9PORT_ERROR_PROCESS_BASE-9)
#define J9PORT_ERROR_PROCESS_COMMAND_LENGTH_ZERO (J9PORT_ERROR_PROCESS_BASE-10)

/** @} */

#define J9PORT_ERROR_SYSTEM_CALL_ERRNO_MASK 0xffff0000
#define J9PORT_ERROR_SYSTEM_CALL_CODE_SHIFT 16

/**
 * @name System V IPC Errors
 * Unix System V IPC function call errno mappings
 * @internal
 * System V errno's for 8 sysv functions:
 * 1 General Function: ftok
 * 3 Semaphore Functions: semget, semctl, semop
 * 4 Memory Functions: shmget, shmctl, shmat, shmdt
 * 
 * The errors are meant to be a 32 bit integer.
 * The most significant 16 bits will identify the failing function 
 * The least significant 16 bits will identify the errno that occured while calling the function
 * 
 * 9 ranges will be used to represent errors starting at the below addresses:
 * 	0xFFFDxxxx for ftok
 * 	0xFFFCxxxx for semget
 * 	0xFFFBxxxx for semctl
 * 	0xFFFAxxxx for semop
 * 	0xFFF9xxxx for shmget
 * 	0xFFF8xxxx for shmctl
 * 	0xFFF7xxxx for shmat
 * 	0xFFF6xxxx for shmdt
 * 	0xFFF5xxxx for __getipc (zOS)
 * @{
 */
#define J9PORT_ERROR_SYSV_IPC_FTOK_ERROR (-2 << J9PORT_ERROR_SYSTEM_CALL_CODE_SHIFT)
#define J9PORT_ERROR_SYSV_IPC_SEMGET_ERROR (-3 << J9PORT_ERROR_SYSTEM_CALL_CODE_SHIFT)
#define J9PORT_ERROR_SYSV_IPC_SEMCTL_ERROR (-4 << J9PORT_ERROR_SYSTEM_CALL_CODE_SHIFT)
#define J9PORT_ERROR_SYSV_IPC_SEMOP_ERROR (-5 << J9PORT_ERROR_SYSTEM_CALL_CODE_SHIFT)
#define J9PORT_ERROR_SYSV_IPC_SHMGET_ERROR (-6 << J9PORT_ERROR_SYSTEM_CALL_CODE_SHIFT)
#define J9PORT_ERROR_SYSV_IPC_SHMCTL_ERROR (-7 << J9PORT_ERROR_SYSTEM_CALL_CODE_SHIFT)
#define J9PORT_ERROR_SYSV_IPC_SHMAT_ERROR (-8 << J9PORT_ERROR_SYSTEM_CALL_CODE_SHIFT)
#define J9PORT_ERROR_SYSV_IPC_SHMDT_ERROR (-9 << J9PORT_ERROR_SYSTEM_CALL_CODE_SHIFT)
#define J9PORT_ERROR_SYSV_IPC_GETIPC_ERROR (-10 << J9PORT_ERROR_SYSTEM_CALL_CODE_SHIFT)

#define J9PORT_ERROR_SYSV_IPC_ERRNO_BASE -600
#define J9PORT_ERROR_SYSV_IPC_ERRNO_EACCES (J9PORT_ERROR_SYSV_IPC_ERRNO_BASE)
#define J9PORT_ERROR_SYSV_IPC_ERRNO_EEXIST (J9PORT_ERROR_SYSV_IPC_ERRNO_BASE-1)
#define J9PORT_ERROR_SYSV_IPC_ERRNO_ENOENT (J9PORT_ERROR_SYSV_IPC_ERRNO_BASE-2)
#define J9PORT_ERROR_SYSV_IPC_ERRNO_EINVAL (J9PORT_ERROR_SYSV_IPC_ERRNO_BASE-3)
#define J9PORT_ERROR_SYSV_IPC_ERRNO_ENOMEM (J9PORT_ERROR_SYSV_IPC_ERRNO_BASE-4)
#define J9PORT_ERROR_SYSV_IPC_ERRNO_ENOSPC (J9PORT_ERROR_SYSV_IPC_ERRNO_BASE-5)
#define J9PORT_ERROR_SYSV_IPC_ERRNO_ELOOP (J9PORT_ERROR_SYSV_IPC_ERRNO_BASE-6)
#define J9PORT_ERROR_SYSV_IPC_ERRNO_ENAMETOOLONG (J9PORT_ERROR_SYSV_IPC_ERRNO_BASE-7) 
#define J9PORT_ERROR_SYSV_IPC_ERRNO_ENOTDIR (J9PORT_ERROR_SYSV_IPC_ERRNO_BASE-8)
#define J9PORT_ERROR_SYSV_IPC_ERRNO_EPERM (J9PORT_ERROR_SYSV_IPC_ERRNO_BASE-9)
#define J9PORT_ERROR_SYSV_IPC_ERRNO_ERANGE (J9PORT_ERROR_SYSV_IPC_ERRNO_BASE-10)
#define J9PORT_ERROR_SYSV_IPC_ERRNO_E2BIG (J9PORT_ERROR_SYSV_IPC_ERRNO_BASE-11)
#define J9PORT_ERROR_SYSV_IPC_ERRNO_EAGAIN (J9PORT_ERROR_SYSV_IPC_ERRNO_BASE-12)
#define J9PORT_ERROR_SYSV_IPC_ERRNO_EFBIG (J9PORT_ERROR_SYSV_IPC_ERRNO_BASE-13)
#define J9PORT_ERROR_SYSV_IPC_ERRNO_EIDRM (J9PORT_ERROR_SYSV_IPC_ERRNO_BASE-14)
#define J9PORT_ERROR_SYSV_IPC_ERRNO_EINTR (J9PORT_ERROR_SYSV_IPC_ERRNO_BASE-15)
#define J9PORT_ERROR_SYSV_IPC_ERRNO_EMFILE (J9PORT_ERROR_SYSV_IPC_ERRNO_BASE-16)
#define J9PORT_ERROR_SYSV_IPC_ERRNO_UNMAPPED (J9PORT_ERROR_SYSV_IPC_ERRNO_BASE-17)
#define J9PORT_ERROR_SYSV_IPC_ERRNO_END J9PORT_ERROR_SYSV_IPC_ERRNO_UNMAPPED


/**
 * Miscellaneous system function call errno mappings
 * @internal
 * Errno for following system call functions:
 * 	getgroups
 *
 * The errors are meant to be a 32 bit integer.
 * The most significant 16 bits will identify the failing function
 * The least significant 16 bits will identify the errno that occured while calling the function
 *
 */
#define J9PORT_ERROR_SYSINFO_GETGROUPSSIZE_ERROR (-2<<16)
#define J9PORT_ERROR_SYSINFO_GETGROUPS_ERROR (-3<<16)

/**
 * @name sysinfo Errors
 * Error codes for sysinfo operations.
 *
 * @internal J9PORT_ERROR_SYSINFO* range from -700 to -750 avoid overlap
 * @{
 */
#define J9PORT_ERROR_SYSINFO_BASE -700
#define J9PORT_ERROR_SYSINFO_OPFAILED (J9PORT_ERROR_SYSINFO_BASE)
#define J9PORT_ERROR_SYSINFO_ENV_INIT_CRASHED_COPYING_BUFFER (J9PORT_ERROR_SYSINFO_BASE-1)
#define J9PORT_ERROR_SYSINFO_GET_STATS_FAILED (J9PORT_ERROR_SYSINFO_BASE-2)
#define J9PORT_ERROR_SYSINFO_INVALID_TIME (J9PORT_ERROR_SYSINFO_BASE-3)
#define J9PORT_ERROR_SYSINFO_QUERY_SETUP_FAILED (J9PORT_ERROR_SYSINFO_BASE-4)
#define J9PORT_ERROR_SYSINFO_NOT_SUPPORTED (J9PORT_ERROR_SYSINFO_BASE-5)
#define J9PORT_ERROR_SYSINFO_INSUFFICIENT_PRIVILEGE (J9PORT_ERROR_SYSINFO_BASE-6)
#define J9PORT_ERROR_SYSINFO_NULL_OBJECT_RECEIVED (J9PORT_ERROR_SYSINFO_BASE-7)
#define J9PORT_ERROR_SYSINFO_ERROR_READING_MEMORY_INFO (J9PORT_ERROR_SYSINFO_BASE-8)
#define J9PORT_ERROR_SYSINFO_PARAM_HAS_INVALID_RANGE (J9PORT_ERROR_SYSINFO_BASE-9)
#define J9PORT_ERROR_SYSINFO_ERROR_READING_PROCESSOR_INFO (J9PORT_ERROR_SYSINFO_BASE-10)
#define J9PORT_ERROR_SYSINFO_MEMORY_ALLOC_FAILED (J9PORT_ERROR_SYSINFO_BASE-11)
#define J9PORT_ERROR_SYSINFO_UNEXPECTED_PROCESSOR_COUNT (J9PORT_ERROR_SYSINFO_BASE-12)

#define J9PORT_ERROR_SYSINFO_ERROR_EINVAL (J9PORT_ERROR_SYSINFO_BASE-13)
#define J9PORT_ERROR_SYSINFO_ERROR_EFAULT (J9PORT_ERROR_SYSINFO_BASE-14)

/**
 * @name Port library initialization return codes
 * Reasons for failure to initialize port library
 */

/* default value */
#define J9PORT_ERROR_INIT_FAIL_BASE -750
#define J9PORT_ERROR_INIT_WRONG_MAJOR_VERSION (J9PORT_ERROR_INIT_FAIL_BASE)
#define J9PORT_ERROR_INIT_WRONG_SIZE (J9PORT_ERROR_INIT_FAIL_BASE - 1)
#define J9PORT_ERROR_INIT_WRONG_CAPABILITIES (J9PORT_ERROR_INIT_FAIL_BASE - 2)

/** @} */

/**
 * @name Read-Write Lock Errors
 * Error code returned by the read-write lock API
 *
 * @internal J9PORT_ERROR_LOCK* range from -800 to -849 avoid overlap
 * @{
 */

#define J9PORT_ERROR_VIRT_RWLOCK_BASE -800
#define J9PORT_ERROR_VIRT_RWLOCK_OPFAILED (J9PORT_ERROR_VIRT_RWLOCK_BASE)
#define J9PORT_ERROR_VIRT_RWLOCK_NOPERMISSION (J9PORT_ERROR_VIRT_RWLOCK_BASE - 1)
#define J9PORT_ERROR_VIRT_RWLOCK_EAGAIN (J9PORT_ERROR_VIRT_RWLOCK_BASE - 2)
#define J9PORT_ERROR_VIRT_RWLOCK_ENOMEM (J9PORT_ERROR_VIRT_RWLOCK_BASE - 3)
#define J9PORT_ERROR_VIRT_RWLOCK_EBUSY (J9PORT_ERROR_VIRT_RWLOCK_BASE - 4)
#define J9PORT_ERROR_VIRT_RWLOCK_EINVAL (J9PORT_ERROR_VIRT_RWLOCK_BASE - 5)
#define J9PORT_ERROR_VIRT_RWLOCK_EDEADLK (J9PORT_ERROR_VIRT_RWLOCK_BASE - 6)
#define J9PORT_ERROR_VIRT_RWLOCK_READER_OVERFLOW (J9PORT_ERROR_VIRT_RWLOCK_BASE - 7)
#define J9PORT_ERROR_VIRT_RWLOCK_READER_UNDERFLOW (J9PORT_ERROR_VIRT_RWLOCK_BASE - 8)
/**
 * @}
 */

/**
 * @name j9hypervisor Errors
 * Error code returned by the j9hypervisor API
 *
 * @internal J9PORT_ERROR_HYPERVISOR* range from -850 to -899 avoid overlap
 * @{
 */
#define J9PORT_ERROR_HYPERVISOR_BASE -850
#define J9PORT_ERROR_HYPERVISOR_CROSSGUEST_MEMORY_UNINIT (J9PORT_ERROR_HYPERVISOR_BASE)
#define J9PORT_ERROR_HYPERVISOR_BAD_HDR_MAGIC (J9PORT_ERROR_HYPERVISOR_BASE - 1)
#define J9PORT_ERROR_HYPERVISOR_BAD_HDR_SIZE (J9PORT_ERROR_HYPERVISOR_BASE - 2)
#define J9PORT_ERROR_HYPERVISOR_MAPPINGFAILED (J9PORT_ERROR_HYPERVISOR_BASE - 3)
#define J9PORT_ERROR_HYPERVISOR_MSYNC_FAILED (J9PORT_ERROR_HYPERVISOR_BASE - 4)
#define J9PORT_ERROR_HYPERVISOR_OPFAILED (J9PORT_ERROR_HYPERVISOR_BASE - 5)
#define J9PORT_ERROR_HYPERVISOR_UNSUPPORTED (J9PORT_ERROR_HYPERVISOR_BASE - 6)
#define J9PORT_ERROR_HYPERVISOR_NO_HYPERVISOR (J9PORT_ERROR_HYPERVISOR_BASE - 7)
#define J9PORT_ERROR_HYPERVISOR_API_UNAVAILABLE (J9PORT_ERROR_HYPERVISOR_BASE - 8)
#define J9PORT_ERROR_HYPERVISOR_CPUINFO_READ_FAILED (J9PORT_ERROR_HYPERVISOR_BASE - 9)
#define J9PORT_ERROR_HYPERVISOR_HOST_INFO_UNAVAILABLE (J9PORT_ERROR_HYPERVISOR_BASE - 10)
#define J9PORT_ERROR_HYPERVISOR_HOST_REQUEST_UNSUPPORTED (J9PORT_ERROR_HYPERVISOR_BASE - 11)
#define J9PORT_ERROR_HYPERVISOR_LPARCFG_MEM_UNSUPPORTED (J9PORT_ERROR_HYPERVISOR_BASE - 12)
#define J9PORT_ERROR_HYPERVISOR_LPARCFG_READ_FAILED (J9PORT_ERROR_HYPERVISOR_BASE - 13)
#define J9PORT_ERROR_HYPERVISOR_MEMORY_ALLOC_FAILED (J9PORT_ERROR_HYPERVISOR_BASE - 14)
#define J9PORT_ERROR_HYPERVISOR_PERFSTAT_CPU_FAILED (J9PORT_ERROR_HYPERVISOR_BASE - 15)
#define J9PORT_ERROR_HYPERVISOR_PERFSTAT_PARTITION_FAILED (J9PORT_ERROR_HYPERVISOR_BASE - 16)
#define J9PORT_ERROR_HYPERVISOR_VMWARE_GUEST_SDK_OP_FAILED (J9PORT_ERROR_HYPERVISOR_BASE - 17)
#define J9PORT_ERROR_HYPERVISOR_VMWARE_GUEST_SDK_OPEN_FAILED (J9PORT_ERROR_HYPERVISOR_BASE - 18)
#define J9PORT_ERROR_HYPERVISOR_VMWARE_HOST_GUESTLIB_NOT_ENABLED (J9PORT_ERROR_HYPERVISOR_BASE - 19)
#define J9PORT_ERROR_HYPERVISOR_VMWARE_UPDATEINFO_NOT_CALLED (J9PORT_ERROR_HYPERVISOR_BASE - 20)
#define J9PORT_ERROR_HYPERVISOR_VMWARE_BUFFER_TOO_SMALL (J9PORT_ERROR_HYPERVISOR_BASE - 21)
#define J9PORT_ERROR_HYPERVISOR_ENV_NOT_SET (J9PORT_ERROR_HYPERVISOR_BASE - 22)
#define J9PORT_ERROR_HYPERVISOR_ENV_VAR_MALFORMED (J9PORT_ERROR_HYPERVISOR_BASE - 23)
#define J9PORT_ERROR_HYPERVISOR_DEFAULTNAME_NOT_SET (J9PORT_ERROR_HYPERVISOR_BASE - 24)
#define J9PORT_ERROR_HYPERVISOR_HYPFS_NOT_MOUNTED (J9PORT_ERROR_HYPERVISOR_BASE - 25)
#define J9PORT_ERROR_HYPERVISOR_HYPFS_READ_FAILED (J9PORT_ERROR_HYPERVISOR_BASE - 26)
#define J9PORT_ERROR_HYPERVISOR_HYPFS_STAT_FAILED (J9PORT_ERROR_HYPERVISOR_BASE - 27)
#define J9PORT_ERROR_HYPERVISOR_HYPFS_UPDATE_OPEN_FAILED (J9PORT_ERROR_HYPERVISOR_BASE - 28)
#define J9PORT_ERROR_HYPERVISOR_HYPFS_UPDATE_WRITE_FAILED (J9PORT_ERROR_HYPERVISOR_BASE - 29)
#define J9PORT_ERROR_HYPERVISOR_HYPFS_UPDATE_LOOP_TIMEOUT (J9PORT_ERROR_HYPERVISOR_BASE - 30)
#define J9PORT_ERROR_HYPERVISOR_SYSINFO_READ_FAILED (J9PORT_ERROR_HYPERVISOR_BASE - 31)
#define J9PORT_ERROR_HYPERVISOR_MACHINE_SPEED_FILE_READ_FAILED (J9PORT_ERROR_HYPERVISOR_BASE - 32)
#define J9PORT_ERROR_HYPERVISOR_LPDAT_QUERY_FAILED (J9PORT_ERROR_HYPERVISOR_BASE - 33)
#define J9PORT_ERROR_HYPERVISOR_CLOCKSPEED_NOT_FOUND (J9PORT_ERROR_HYPERVISOR_BASE - 34)

/**
 * @name j9str Errors
 * Error code returned by the string processing API
 *
 * @internal J9PORT_ERROR_STRING_* range from -900 to -950 avoid overlap
 * @{
 */
#define J9PORT_ERROR_STRING_BASE -900
#define J9PORT_ERROR_STRING_ILLEGAL_STRING (J9PORT_ERROR_STRING_BASE - 0)
#define J9PORT_ERROR_STRING_BUFFER_TOO_SMALL (J9PORT_ERROR_STRING_BASE - 1)
#define J9PORT_ERROR_STRING_ICONV_OPEN_FAILED (J9PORT_ERROR_STRING_BASE - 2)
#define J9PORT_ERROR_STRING_UNSUPPORTED_ENCODING (J9PORT_ERROR_STRING_BASE - 3)
#define J9PORT_ERROR_STRING_MEM_ALLOCATE_FAILED (J9PORT_ERROR_STRING_BASE - 4)
/**
 * @}
 */

#endif     /* j9porterror_h */


